### ISSUE TITLE
ZIP file is empty

### ISSUE THREAD

**Issue by hagenburger** [bBoxType/FiraGO#2]

**Comment by carrois** [comment]
Hi. File transfer error. Should be fine now.

**Comment by davelab6** [comment]
A 95Mb zip file in a git repo is hardly better than a 0mb file ;)

For release ZIPs, I suggest using the https://github.com/bBoxType/FiraGO/releases system and not bulking up the repo with ZIP files that duplicate files existing in the repo already :)

**Comment by carrois** [comment]
Ok?
