### ISSUE TITLE
g is inconsistent

### ISSUE THREAD

**Issue by domoritz** [bBoxType/FiraGO#21]
The g from the regular and the italic font are inconsistent. Why is that?

<img width="76" alt="screen shot 2018-09-08 at 20 47 33" src="https://user-images.githubusercontent.com/589034/45260909-87dbb280-b3a8-11e8-9f7f-101af46d932f.png">
<img width="79" alt="screen shot 2018-09-08 at 20 47 30" src="https://user-images.githubusercontent.com/589034/45260911-89a57600-b3a8-11e8-895e-2448e6662334.png">

**Comment by carrois** [comment]
This is no inconsistency but a fundamental difference between Roman and Italic style running through all weights (not only regular). The Italic style refers to the act of writing. As for that, there are more fluent shapes compared to the upright Roman style. The single-story a and g, and an f with descender, a rounded e, ... are the most common ones. Have a looks at other fonts, you will notice the same differences. Some typefaces offer a "simply slanted" style called "Oblique" without altered letter shapes (Fira does not).

**Comment by domoritz** [comment]
Thank you for the response. It's impressive how many things you notice once you pay attention to them.
