### ISSUE TITLE
[question] technical report generator?

### ISSUE THREAD

**Issue by ghost** [bBoxType/FiraGO#44]
Hello, I really like the PDF design of the Technical Reports.  
would it be possible for you to share your generator program?  
(or how it works?)

The PDF's META-data has the <code>Creator</code> tag with: <code>Tech Report Program written by Mark Frömberg</code>, and the <code>Producer</code> tag with: <code>Mac OS X 10.13.2 Quartz PDFContext</code>.

thanks!

<hr/>

Edit:  
I did find two alternatives, 
both will analyse a TTF-file.  

https://github.com/eugmes/fntsample  
and https://github.com/googlefonts/fontreport  

They do, however, require a linux operation-system,  
(although Windows users might be able to use Cygwin).

And I guess writing a small script to work with FontForge is also an option (I was pretty shocked to find out a report generation is not an already a built-in feature).

**Comment by kenmcd** [comment]
Same request here.
Tried to track this down myself months ago.
I did find a python script which did something similar, so I assumed this may incorporate that code.
Lost the link to that script and cannot find it again.
I assume this is a custom script - which is unlikely to get shared.
But maybe they will share the source or inspiration for the report-creating code.
Sooooo . . .
What is the source or inspiration for this report?
