### ISSUE TITLE
Bad hinting of 'e' in Bold Italic and ExtraBold Italic weights

### ISSUE THREAD

**Issue by NDPtype** [bBoxType/FiraGO#48]
I am using FiraGO, but I don't like the design of the italic 'e' in the Bold Italic and ExtraBold Italic, so can someone fix this for me, please?
![firago e issue](https://user-images.githubusercontent.com/105497069/168282736-e3b1be04-b846-41c9-9ce1-e84c697196e9.png)

**Comment by carrois** [comment]
Hi.
Sorry, for the delay … though we can not find this issue in our fonts.
Please double check.
Thanks.

**Comment by NDPtype** [comment]
The version of FiraGO that I have on my computer (1.001) has this issue.

**Comment by NDPtype** [comment]
So, can u pls give me a version with this fixed?

**Comment by NDPtype** [comment]
Please redesign the "e". I don't like this one.

**Comment by carrois** [comment]
https://bboxtype.com/fira/


type is the air we read _ ralph du carrois
