### ISSUE TITLE
Request/idea: stylistic set for the number 4

### ISSUE THREAD

**Issue by khawkins98** [bBoxType/FiraGO#9]
Hi there. First off, great to see effort being but into the Fira lineage!

When using Fira in large tables of numbers we've found the spacing and legibility to be a bit problematic without some manual tweaking. 

A lot of that is of course corrected by using tabular figures (on the web `font-variant-numeric: tabular-nums;`), however [we're finding](https://github.com/ebiwd/EBI-Icon-fonts/issues/8#issuecomment-353985034) the number 4 to still be an issue.

Would you be supportive of a new stylistic set (sso5?) with closed number 4?

That is, something like:
![image](https://user-images.githubusercontent.com/928100/37512668-b29e8634-28fa-11e8-9015-bd9be08e41f4.png)

#notAFontDesigner

**Comment by carrois** [comment]
Will be added in the next version (coming this week) accessible via stylistic set 06.

**Comment by khawkins98** [comment]
That's fantastic. Thanks for being open to it.
